// <auto-generated />
using System;
using System.Collections.Generic;
using HotelBooking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelBooking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HotelBookingDbContext))]
    [Migration("20260927112750_AddHotelsCityNameIdIndex")]
    partial class AddHotelsCityNameIdIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelBooking.Domain.Amenities.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Amenities_Slug")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Amenities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ba4f778-b85a-4c3e-95f7-3cc6af85da0a"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Wireless internet throughout the property, at no extra charge.",
                            IsDeleted = false,
                            Name = "Free Wi-Fi",
                            Slug = "free-wifi"
                        },
                        new
                        {
                            Id = new Guid("dd7e6adc-5a52-4f97-b3ae-f8728d04c0d3"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "On-site parking for guests, free or paid.",
                            IsDeleted = false,
                            Name = "Parking",
                            Slug = "parking"
                        },
                        new
                        {
                            Id = new Guid("9486e728-f6db-4ee8-8232-2f2480f5d098"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A pool guests may use, indoor or outdoor.",
                            IsDeleted = false,
                            Name = "Swimming Pool",
                            Slug = "swimming-pool"
                        },
                        new
                        {
                            Id = new Guid("f530aac0-55f4-4536-88f8-35b39c9c3d6d"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Cooling a guest controls from the room.",
                            IsDeleted = false,
                            Name = "Air Conditioning",
                            Slug = "air-conditioning"
                        },
                        new
                        {
                            Id = new Guid("95bc7403-568b-4e26-be5e-2ca051dd044e"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Breakfast served daily and included in the rate.",
                            IsDeleted = false,
                            Name = "Breakfast Included",
                            Slug = "breakfast-included"
                        },
                        new
                        {
                            Id = new Guid("fd637415-faef-4f8f-bb7c-d84ed303ee9c"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "At least one restaurant on the property.",
                            IsDeleted = false,
                            Name = "Restaurant",
                            Slug = "restaurant"
                        },
                        new
                        {
                            Id = new Guid("c7846376-5c39-4dd3-8ebf-aad067cca5bb"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A gym guests may use during their stay.",
                            IsDeleted = false,
                            Name = "Fitness Centre",
                            Slug = "fitness-centre"
                        },
                        new
                        {
                            Id = new Guid("de9a841f-14b6-4254-8f12-84ecacf9a359"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Spa or wellness treatments available on site.",
                            IsDeleted = false,
                            Name = "Spa",
                            Slug = "spa"
                        },
                        new
                        {
                            Id = new Guid("05bb28ac-08c1-469e-a1ad-34b2bfdb5878"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Food and drink brought to the room.",
                            IsDeleted = false,
                            Name = "Room Service",
                            Slug = "room-service"
                        },
                        new
                        {
                            Id = new Guid("acdd7355-8d42-401a-8a51-d2d53aa6fb90"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A shuttle between the property and the airport.",
                            IsDeleted = false,
                            Name = "Airport Shuttle",
                            Slug = "airport-shuttle"
                        },
                        new
                        {
                            Id = new Guid("c6c1d494-dcf9-4d47-a677-5c10889c1230"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Rooms laid out for families travelling with children.",
                            IsDeleted = false,
                            Name = "Family Rooms",
                            Slug = "family-rooms"
                        },
                        new
                        {
                            Id = new Guid("65714b0f-b41a-42a4-9f3a-b4c4180ee110"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Guests may bring pets, sometimes for a fee.",
                            IsDeleted = false,
                            Name = "Pet Friendly",
                            Slug = "pet-friendly"
                        },
                        new
                        {
                            Id = new Guid("1d965abe-6bab-403c-8706-315c5ca91769"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Entrance, reception and lifts reachable without steps.",
                            IsDeleted = false,
                            Name = "Step-Free Access",
                            Slug = "step-free-access"
                        });
                });

            modelBuilder.Entity("HotelBooking.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CancellationReason")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Confirmation")
                        .IsRequired()
                        .HasMaxLength(17)
                        .IsUnicode(false)
                        .HasColumnType("varchar(17)")
                        .HasColumnName("ConfirmationNumber");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("EarliestCheckIn")
                        .HasColumnType("date")
                        .HasColumnName("CheckIn");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("LatestCheckOut")
                        .HasColumnType("date")
                        .HasColumnName("CheckOut");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalPrice", "HotelBooking.Domain.Bookings.Booking.TotalPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(false)
                                .HasColumnType("char(3)")
                                .HasColumnName("TotalCurrency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id");

                    b.HasIndex("Confirmation")
                        .IsUnique()
                        .HasDatabaseName("IX_Bookings_ConfirmationNumber");

                    b.HasIndex("HotelId");

                    b.HasIndex(new[] { "UserId", "CreatedAtUtc", "Id" }, "IX_Bookings_UserId_CreatedAtUtc_Id")
                        .IsDescending(false, true, true);

                    b.HasIndex(new[] { "UserId" }, "IX_Bookings_UserId_Pending")
                        .IsUnique()
                        .HasFilter("[Status] = 0");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("HotelBooking.Domain.Bookings.BookingLine", b =>
                {
                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DiscountTotal", "HotelBooking.Domain.Bookings.BookingLine.DiscountTotal#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("DiscountAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(false)
                                .HasColumnType("char(3)")
                                .HasColumnName("DiscountCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Guests", "HotelBooking.Domain.Bookings.BookingLine.Guests#Occupancy", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Adults")
                                .HasColumnType("int")
                                .HasColumnName("Adults");

                            b1.Property<int>("Children")
                                .HasColumnType("int")
                                .HasColumnName("Children");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "LineTotal", "HotelBooking.Domain.Bookings.BookingLine.LineTotal#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("LineAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(false)
                                .HasColumnType("char(3)")
                                .HasColumnName("LineCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "NightlyRate", "HotelBooking.Domain.Bookings.BookingLine.NightlyRate#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("NightlyAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(false)
                                .HasColumnType("char(3)")
                                .HasColumnName("NightlyCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Stay", "HotelBooking.Domain.Bookings.BookingLine.Stay#DateRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("CheckIn")
                                .HasColumnType("date")
                                .HasColumnName("CheckIn");

                            b1.Property<DateOnly>("CheckOut")
                                .HasColumnType("date")
                                .HasColumnName("CheckOut");
                        });

                    b.HasKey("BookingId", "LineNumber")
                        .HasName("PK_BookingLines");

                    b.HasIndex("RoomId");

                    b.ToTable("BookingLines", (string)null);
                });

            modelBuilder.Entity("HotelBooking.Domain.Bookings.RoomNight", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StayDate")
                        .HasColumnType("date");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoomId", "StayDate")
                        .HasName("PK_RoomNightInventory");

                    b.HasIndex("BookingId");

                    b.ToTable("RoomNightInventory", (string)null);
                });

            modelBuilder.Entity("HotelBooking.Domain.Cities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostOffice")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Cities_Name")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("Country", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Cities_Country_Name")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("HotelBooking.Domain.Deals.Deal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Discount", "HotelBooking.Domain.Deals.Deal.Discount#DiscountPercentage", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("DiscountPercentage");
                        });

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("StartsOn", "EndsOn")
                        .HasDatabaseName("IX_Deals_Live")
                        .HasFilter("[IsFeatured] = 1 AND [IsDeleted] = 0");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("StartsOn", "EndsOn"), new[] { "RoomId", "HotelId" });

                    b.HasIndex("RoomId", "StartsOn", "EndsOn")
                        .HasDatabaseName("IX_Deals_RoomId_StartsOn_EndsOn")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Deals", (string)null);
                });

            modelBuilder.Entity("HotelBooking.Domain.Deals.DealNight", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StayDate")
                        .HasColumnType("date");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoomId", "StayDate")
                        .HasName("PK_DealNights");

                    b.HasIndex("DealId");

                    b.ToTable("DealNights", (string)null);
                });

            modelBuilder.Entity("HotelBooking.Domain.Hotels.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StarRating")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "HotelBooking.Domain.Hotels.Hotel.Location#GeoLocation", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("Latitude");

                            b1.Property<decimal>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("Longitude");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Hotels_Name")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("CityId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Hotels_CityId_Name")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("CityId", "StarRating")
                        .HasDatabaseName("IX_Hotels_CityId_StarRating")
                        .HasFilter("[IsDeleted] = 0");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CityId", "StarRating"), new[] { "Name", "ThumbnailUrl" });

                    b.HasIndex("CityId", "Name", "Id")
                        .HasDatabaseName("IX_Hotels_CityId_Name_Id")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Hotels", (string)null);
                });

            modelBuilder.Entity("HotelBooking.Domain.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId", "Key")
                        .HasName("PK_IdempotencyRecords");

                    b.ToTable("IdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("HotelBooking.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CheckoutUrl")
                        .HasMaxLength(2048)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2048)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProviderCheckoutId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderPaymentId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderRefundId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset?>("RefundRequestedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RefundResolvedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "HotelBooking.Domain.Payments.Payment.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(false)
                                .HasColumnType("char(3)")
                                .HasColumnName("Currency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("IX_Payments_BookingId");

                    b.HasIndex("ProviderCheckoutId")
                        .IsUnique()
                        .HasDatabaseName("IX_Payments_ProviderCheckoutId")
                        .HasFilter("[ProviderCheckoutId] IS NOT NULL");

                    b.HasIndex(new[] { "ExpiresAtUtc" }, "IX_Payments_Pending_ExpiresAtUtc")
                        .HasFilter("[Status] = 0");

                    b.HasIndex(new[] { "RefundRequestedAtUtc" }, "IX_Payments_Refunding_RefundRequestedAtUtc")
                        .HasFilter("[Status] = 3");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("HotelBooking.Domain.RefreshTokens.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("IX_RefreshTokens_FamilyId")
                        .HasFilter("[RevokedAtUtc] IS NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_TokenHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_UserId")
                        .HasFilter("[RevokedAtUtc] IS NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("UserId"), new[] { "FamilyId" });

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("HotelBooking.Domain.Rooms.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BasePrice", "HotelBooking.Domain.Rooms.Room.BasePrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("BasePrice");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(false)
                                .HasColumnType("char(3)")
                                .HasColumnName("BasePriceCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Capacity", "HotelBooking.Domain.Rooms.Room.Capacity#Occupancy", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Adults")
                                .HasColumnType("int")
                                .HasColumnName("AdultCapacity");

                            b1.Property<int>("Children")
                                .HasColumnType("int")
                                .HasColumnName("ChildrenCapacity");
                        });

                    b.HasKey("Id");

                    b.HasIndex("HotelId", "Number")
                        .IsUnique()
                        .HasDatabaseName("IX_Rooms_HotelId_Number")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("HotelBooking.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("HotelBooking.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessingAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(55)
                        .IsUnicode(false)
                        .HasColumnType("varchar(55)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredOnUtc")
                        .HasDatabaseName("IX_OutboxMessages_Unprocessed")
                        .HasFilter("[ProcessedOnUtc] IS NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("OccurredOnUtc"), new[] { "Type", "Content", "Attempts", "ProcessingAtUtc", "TraceParent" });

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("HotelBooking.Domain.Bookings.Booking", b =>
                {
                    b.HasOne("HotelBooking.Domain.Hotels.Hotel", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelBooking.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelBooking.Domain.Bookings.BookingLine", b =>
                {
                    b.HasOne("HotelBooking.Domain.Bookings.Booking", null)
                        .WithMany("Lines")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookingLines_Bookings");

                    b.HasOne("HotelBooking.Domain.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelBooking.Domain.Bookings.RoomNight", b =>
                {
                    b.HasOne("HotelBooking.Domain.Bookings.Booking", null)
                        .WithMany("Nights")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RoomNightInventory_Bookings");

                    b.HasOne("HotelBooking.Domain.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelBooking.Domain.Deals.Deal", b =>
                {
                    b.HasOne("HotelBooking.Domain.Hotels.Hotel", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelBooking.Domain.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelBooking.Domain.Deals.DealNight", b =>
                {
                    b.HasOne("HotelBooking.Domain.Deals.Deal", null)
                        .WithMany("Nights")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DealNights_Deals");

                    b.HasOne("HotelBooking.Domain.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelBooking.Domain.Hotels.Hotel", b =>
                {
                    b.HasOne("HotelBooking.Domain.Cities.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("HotelBooking.Domain.Hotels.HotelAmenityLink", "AmenityLinks", b1 =>
                        {
                            b1.Property<Guid>("HotelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("AmenityId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("HotelId", "AmenityId");

                            b1.HasIndex("AmenityId");

                            b1.ToTable("HotelAmenities", (string)null);

                            b1.HasOne("HotelBooking.Domain.Amenities.Amenity", null)
                                .WithMany()
                                .HasForeignKey("AmenityId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("HotelId");
                        });

                    b.OwnsMany("HotelBooking.Domain.Hotels.HotelImage", "Images", b1 =>
                        {
                            b1.Property<Guid>("HotelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Position")
                                .HasColumnType("int");

                            b1.Property<string>("Caption")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("nvarchar(2048)");

                            b1.HasKey("HotelId", "Position");

                            b1.ToTable("HotelImages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("HotelId");
                        });

                    b.Navigation("AmenityLinks");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("HotelBooking.Domain.Payments.Payment", b =>
                {
                    b.HasOne("HotelBooking.Domain.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelBooking.Domain.RefreshTokens.RefreshToken", b =>
                {
                    b.HasOne("HotelBooking.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelBooking.Domain.Rooms.Room", b =>
                {
                    b.HasOne("HotelBooking.Domain.Hotels.Hotel", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelBooking.Domain.Users.User", b =>
                {
                    b.OwnsMany("HotelBooking.Domain.Users.UserRoleGrant", "Roles", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Role")
                                .HasColumnType("int");

                            b1.Property<DateTimeOffset>("GrantedAtUtc")
                                .HasColumnType("datetimeoffset");

                            b1.HasKey("UserId", "Role");

                            b1.ToTable("UserRoles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("HotelBooking.Domain.Bookings.Booking", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Nights");
                });

            modelBuilder.Entity("HotelBooking.Domain.Deals.Deal", b =>
                {
                    b.Navigation("Nights");
                });
#pragma warning restore 612, 618
        }
    }
}
